# Usa una imagen base de Node.js ligera
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de manifiesto del proyecto
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto del servidor de desarrollo de Vue
EXPOSE 8080

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]