services:
  backend:
    build: ./backend
    container_name: validador_qm_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: validador_qm_frontend
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always