# docker-compose.prod.yml (VERSIÓN FINAL PARA CI/CD Y DESPLIEGUE EN AWS)

# Esta versión está diseñada para ser usada por el pipeline de CI/CD.
# No construye las imágenes en el servidor, sino que las descarga desde un
# registro de contenedores (ECR) donde el pipeline las ha subido previamente.

services:
  #--- SERVICIO DE PROXY Y FRONTEND (NGINX + VUE) ---
  frontend:
    # La directiva 'build' se reemplaza por 'image'.
    # Las variables ${ECR_REGISTRY} y ${IMAGE_TAG} serán exportadas
    # en el servidor EC2 por el script del pipeline de GitHub Actions.
    image: ${ECR_REGISTRY}/validador-qm-frontend:${IMAGE_TAG}
    container_name: validador_qm_frontend_prod
    restart: always
    ports:
      # Este es el único punto de entrada público a la aplicación.
      # Mapea el puerto 80 del servidor EC2 al puerto 8080 de Nginx.
      - "80:8080"
    networks:
      - validador-net-prod
    depends_on:
      - backend
      - n8n

  #--- SERVICIO DE BACKEND (FLASK) ---
  backend:
    image: ${ECR_REGISTRY}/validador-qm-backend:${IMAGE_TAG}
    container_name: validador_qm_backend_prod
    restart: always
    env_file:
      - .env.prod
    # No se exponen puertos al exterior; solo Nginx (frontend) habla con el backend.
    networks:
      - validador-net-prod
    depends_on:
      - n8n
      - postgres

  #--- SERVICIO DE ORQUESTACIÓN (N8N) ---
  n8n:
    image: ${ECR_REGISTRY}/validador-qm-n8n:${IMAGE_TAG}
    container_name: validador_qm_n8n_prod
    restart: always
    env_file:
      - .env.prod
    environment:
      # Las variables se cargan desde env_file, pero se listan aquí para claridad.
      # El entrypoint.sh dentro de la imagen usará estas para el setup.
      N8N_OWNER_EMAIL: ${N8N_OWNER_EMAIL}
      N8N_OWNER_PASSWORD: ${N8N_OWNER_PASSWORD}
      # Configuración de la base de datos
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      # Clave de cifrado y configuración de proxy
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_PROXY_MODE: ${N8N_PROXY_MODE}
      WEBHOOK_URL: ${WEBHOOK_URL}
    volumes:
      - n8n_data_prod:/home/node/.n8n
    secrets:
      - n8n_credentials
    networks:
      - validador-net-prod
    depends_on:
      - postgres

  #--- SERVICIO DE BASE DE DATOS (POSTGRESQL) ---
  postgres:
    # Este servicio no cambia, siempre usa una imagen pública de Docker Hub.
    image: postgres:13
    container_name: validador_qm_postgres_prod
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - validador-net-prod

networks:
  validador-net-prod:
    driver: bridge

volumes:
  n8n_data_prod:
  postgres_data_prod:

secrets:
  n8n_credentials:
    file: ./n8n_credentials.json