services:
  backend:
    build: ./backend
    container_name: validador_qm_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: always
    networks:
      - validador-net

  frontend:
    build: ./frontend
    container_name: validador_qm_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
    networks:
      - validador-net

  # --- NUEVO SERVICIO N8N ---
  n8n:
    image: n8nio/n8n:latest
    container_name: validador_qm_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - validador-net

# --- NUEVA RED COMPARTIDA ---
networks:
  validador-net:
    driver: bridge