# docker-compose.prod.yml

services:
  frontend:
    image: ${ECR_REGISTRY}/validador-qm-frontend:${IMAGE_TAG}
    container_name: validador_qm_frontend_prod
    restart: always
    ports: ["80:8080"]
    networks: ["validador-net-prod"]
    depends_on: [backend, n8n]

  backend:
    image: ${ECR_REGISTRY}/validador-qm-backend:${IMAGE_TAG}
    container_name: validador_qm_backend_prod
    restart: always
    env_file: [".env.prod"]
    networks: ["validador-net-prod"]
    depends_on: [n8n, postgres]

  n8n:
    image: ${ECR_REGISTRY}/validador-qm-n8n:${IMAGE_TAG}
    container_name: validador_qm_n8n_prod
    restart: always
    env_file: [".env.prod"]
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_PROXY_MODE: ${N8N_PROXY_MODE}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_PATH: ${N8N_PATH}
    volumes: ["n8n_data_prod:/home/node/.n8n"]
    networks: ["validador-net-prod"]
    depends_on: [postgres]

  postgres:
    image: postgres:13
    container_name: validador_qm_postgres_prod
    restart: always
    env_file: [".env.prod"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: ["postgres_data_prod:/var/lib/postgresql/data"]
    networks: ["validador-net-prod"]

networks:
  validador-net-prod:
    driver: bridge

volumes:
  n8n_data_prod:
  postgres_data_prod: