# n8n_custom/Dockerfile.prod (CON WORKFLOWS HORNEADOS)

FROM n8nio/n8n:latest

USER root
RUN apk add --no-cache pandoc poppler-utils curl grep

# ¡NUEVO! Creamos la carpeta y copiamos los workflows DENTRO de la imagen.
RUN mkdir -p /home/node/workflows/
COPY ./n8n_workflows/*.json /home/node/workflows/

# Copiamos el entrypoint
COPY ./n8n_custom/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

USER node
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]