# n8n_custom/Dockerfile.dev

FROM docker.n8n.io/n8nio/n8n:latest

USER root
RUN apk add --no-cache pandoc poppler-utils

# ¡CAMBIO CLAVE! Copiamos y preparamos nuestro nuevo entrypoint de desarrollo.
COPY ./n8n_custom/entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

USER node

# Le decimos a la imagen que use nuestro script como punto de entrada.
ENTRYPOINT ["/usr/local/bin/entrypoint.dev.sh"]