# .github/workflows/deploy.yml

name: Build and Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag
        id: image_tag
        run: echo "tag=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      # --- ETAPA DE BUILD & PUSH (EN GITHUB) ---
      
      - name: Build and push Backend image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/validador-qm-backend:${{ steps.image_tag.outputs.tag }} -f backend/Dockerfile .
          docker push ${{ steps.login-ecr.outputs.registry }}/validador-qm-backend:${{ steps.image_tag.outputs.tag }}

      - name: Build and push Frontend image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/validador-qm-frontend:${{ steps.image_tag.outputs.tag }} --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} --build-arg VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }} -f frontend/Dockerfile .
          docker push ${{ steps.login-ecr.outputs.registry }}/validador-qm-frontend:${{ steps.image_tag.outputs.tag }}

      - name: Build and push n8n image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/validador-qm-n8n:${{ steps.image_tag.outputs.tag }} -f n8n_custom/Dockerfile.prod .
          docker push ${{ steps.login-ecr.outputs.registry }}/validador-qm-n8n:${{ steps.image_tag.outputs.tag }}
          
      # --- ETAPA DE DEPLOY (EN EC2) ---

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ¡NUEVO! Salir inmediatamente si cualquier comando falla.
            set -e

            cd ~/validadorQM
            git checkout main
            # Usamos 'git reset --hard' para asegurar un estado limpio
            git reset --hard origin/main
            git pull origin main
            
            # Crear los archivos de secretos
            echo "${{ secrets.ENV_PROD_CONTENT }}" > .env.prod
            echo "${{ secrets.N8N_CREDENTIALS_JSON }}" > n8n_credentials.json
            
            # Exportar variables
            export IMAGE_TAG=${{ steps.image_tag.outputs.tag }}
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          
            # Autenticar Docker con ECR. Si esto falla, el script se detendrá.
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            
            # Descargar las nuevas imágenes.
            # ¡CAMBIO! Añadimos el --env-file para eliminar las advertencias.
            docker compose -p validadorqm_prod -f docker-compose.prod.yml --env-file .env.prod pull
            
            # Reiniciar los servicios.
            docker compose -p validadorqm_prod -f docker-compose.prod.yml --env-file .env.prod up -d --force-recreate
            
            docker image prune -f