# .github/workflows/deploy.yml

name: Deploy n8n Workflows via API

on:
  push:
    branches: [ "main" ]

jobs:
  # Job para detectar cambios en los workflows
  detect-workflow-changes:
    runs-on: ubuntu-latest
    outputs:
      # ¡CAMBIO CLAVE! Usamos el output que ya está formateado como JSON.
      changed_workflows_json: ${{ steps.changed-files.outputs.all_changed_files_as_json }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find changed workflow files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: n8n_workflows/**.json

  # Job que se ejecuta para CADA workflow que ha cambiado.
  deploy-workflows:
    needs: detect-workflow-changes
    # ¡CAMBIO CLAVE! La condición ahora comprueba si el array JSON no está vacío.
    if: needs.detect-workflow-changes.outputs.changed_workflows_json != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Usamos el output JSON correcto para construir la matriz.
        workflow: ${{ fromJson(needs.detect-workflow-changes.outputs.changed_workflows_json) }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy ${{ matrix.workflow }}
        env:
          N8N_API_KEY: ${{ secrets.N8N_PROD_API_KEY }}
          N8N_URL: http://44.209.113.21/n8n # La URL pública de tu n8n
        run: |
          echo "Deploying ${{ matrix.workflow }}..."
          
          # Extraemos el ID del workflow del propio archivo JSON
          WORKFLOW_ID=$(cat "${{ matrix.workflow }}" | grep '"id":' | head -n 1 | awk -F'"' '{print $4}')
          
          if [ -z "$WORKFLOW_ID" ]; then
            echo "Error: Could not find workflow ID in ${{ matrix.workflow }}"
            exit 1
          fi
          
          echo "Found Workflow ID: $WORKFLOW_ID"
          
          # Usamos PUT para actualizar el workflow existente por su ID.
          # Esto es seguro y no afecta a otros workflows.
          # Añadimos la opción -S para mostrar errores de curl pero no la barra de progreso.
          curl --fail -S -X PUT "${N8N_URL}/api/v1/workflows/${WORKFLOW_ID}" \
            -H "Authorization: Bearer ${N8N_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @"${{ matrix.workflow }}"